Print solved dependency graph
revng/orchestra pull request #8
Opened 2021-01-07 09:36 UTC by fcremo

With this PR the CI scripts will print the full graph of all the components known to orchestra (not limited to revng-distributable) and the solved graph for the requested component.
This will aid debugging orchestra action scheduler.

2021-01-12 11:26 UTC, aleclearmind requested changes

2021-01-12 11:26 UTC, aleclearmind commented on .orchestra/ci/ci.sh
> +fi
This early exit introduces the risk that if we append something at the end of the script it accidentally skipped.
Wrap the rest of the code in the `if`.

2021-01-12 11:26 UTC, aleclearmind commented on .orchestra/ci/ci.sh
> +if [ "$PUSH_CHANGES" != 1 ]; then
Please use `test`, for coherence's sake.

2021-01-12 13:24 UTC, aleclearmind commented
This MR blocked by stabilizing the CI hook receiver

2021-01-13 09:29 UTC, fcremo commented
@aleclearmind I fixed the issues you pointed out and added the CI hook script

2021-01-22 15:16 UTC, aleclearmind commented
Please squash fixup commits in PRs.

Group to be merged (PUSH_CHANGES):
915c6053446ae4384ec9fda54bb1eca5704c27fa
f2bf08f2552f31fdce82a227322650ecfa11b8ee
eebabd821299495b26edde7301528f210e027dc8 (last part)

Group to be merged:
d9853f064e06a95f6767a36ed824ea7521cd223f
68f79270f5ad6b43b34c72cca2a67ce02cc0d85b

Group to be merged (improve CI):
383e10dfacc4764ffd2626f168d42efd42d10682
5313b2a0cd228f178a85c1d05d6c4415addc16f3

I expect the following commits:
* eebabd821299495b26edde7301528f210e027dc8 (first part)
* One for `PUSH_CHANGES`
* One for `ci-hook`
* Improve CI debuggability
* Ignore JSON config cache

2021-02-02 13:32 UTC, fcremo commented
Closing this, it has been merged in a1dd992ee58e716973182a4db522a7930ec67004

2021-02-02 13:32 UTC, closed without merging